CREATE TABLE SAP(
ID  SERIAL PRIMARY KEY,
gender  VARCHAR(100),
NationalITy VARCHAR(100),
PlaceofBirth    VARCHAR(100),
StageID VARCHAR(100),
GradeID VARCHAR(100),
SectionID   VARCHAR(100),
Topic   VARCHAR(100),
Semester    VARCHAR(100),
Relation    VARCHAR(100),
raisedhands INT,
VisITedResources    INT,
AnnouncementsView   INT,
Discussion  INT,
ParentAnsweringSurvey   VARCHAR(100),
ParentschoolSatisfaction    VARCHAR(100),
StudentAbsenceDays  VARCHAR(100),
Class   VARCHAR(100)
);