"""empty message

Revision ID: 0cd2540a295f
Revises: 
Create Date: 2016-12-07 15:49:38.226857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cd2540a295f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migrate_version')
    op.drop_table('users')
    op.drop_table('us_elections')
    op.add_column('sap', sa.Column('AnnouncementsView', sa.Integer(), nullable=True))
    op.add_column('sap', sa.Column('Class', sa.String(), nullable=True))
    op.add_column('sap', sa.Column('Discussion', sa.Integer(), nullable=True))
    op.add_column('sap', sa.Column('GradeID', sa.String(), nullable=True))
    op.add_column('sap', sa.Column('NationalITy', sa.String(), nullable=True))
    op.add_column('sap', sa.Column('ParentAnsweringSurvey', sa.String(), nullable=True))
    op.add_column('sap', sa.Column('ParentschoolSatisfaction', sa.String(), nullable=True))
    op.add_column('sap', sa.Column('PlaceofBirth', sa.String(), nullable=True))
    op.add_column('sap', sa.Column('Relation', sa.String(), nullable=True))
    op.add_column('sap', sa.Column('SectionID', sa.String(), nullable=True))
    op.add_column('sap', sa.Column('Semester', sa.String(), nullable=True))
    op.add_column('sap', sa.Column('StageID', sa.String(), nullable=True))
    op.add_column('sap', sa.Column('StudentAbsenceDays', sa.String(), nullable=True))
    op.add_column('sap', sa.Column('Topic', sa.String(), nullable=True))
    op.add_column('sap', sa.Column('VisITedResources', sa.Integer(), nullable=True))
    op.drop_column('sap', 'visitedresources')
    op.drop_column('sap', 'announcementsview')
    op.drop_column('sap', 'sectionid')
    op.drop_column('sap', 'gradeid')
    op.drop_column('sap', 'discussion')
    op.drop_column('sap', 'class')
    op.drop_column('sap', 'topic')
    op.drop_column('sap', 'studentabsencedays')
    op.drop_column('sap', 'semester')
    op.drop_column('sap', 'relation')
    op.drop_column('sap', 'parentansweringsurvey')
    op.drop_column('sap', 'stageid')
    op.drop_column('sap', 'parentschoolsatisfaction')
    op.drop_column('sap', 'nationality')
    op.drop_column('sap', 'placeofbirth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sap', sa.Column('placeofbirth', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('sap', sa.Column('nationality', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('sap', sa.Column('parentschoolsatisfaction', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('sap', sa.Column('stageid', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('sap', sa.Column('parentansweringsurvey', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('sap', sa.Column('relation', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('sap', sa.Column('semester', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('sap', sa.Column('studentabsencedays', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('sap', sa.Column('topic', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('sap', sa.Column('class', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('sap', sa.Column('discussion', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sap', sa.Column('gradeid', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('sap', sa.Column('sectionid', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('sap', sa.Column('announcementsview', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sap', sa.Column('visitedresources', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('sap', 'VisITedResources')
    op.drop_column('sap', 'Topic')
    op.drop_column('sap', 'StudentAbsenceDays')
    op.drop_column('sap', 'StageID')
    op.drop_column('sap', 'Semester')
    op.drop_column('sap', 'SectionID')
    op.drop_column('sap', 'Relation')
    op.drop_column('sap', 'PlaceofBirth')
    op.drop_column('sap', 'ParentschoolSatisfaction')
    op.drop_column('sap', 'ParentAnsweringSurvey')
    op.drop_column('sap', 'NationalITy')
    op.drop_column('sap', 'GradeID')
    op.drop_column('sap', 'Discussion')
    op.drop_column('sap', 'Class')
    op.drop_column('sap', 'AnnouncementsView')
    op.create_table('us_elections',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('county', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fips', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cand', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('st', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('votes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('total_votes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('lead', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'us_elections_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'users_pkey')
    )
    op.create_table('migrate_version',
    sa.Column('repository_id', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('repository_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('repository_id', name=u'migrate_version_pkey')
    )
    # ### end Alembic commands ###
