"""empty message

Revision ID: 6f0c16fcaa05
Revises: d28ab2660e71
Create Date: 2016-12-12 14:44:14.120462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0c16fcaa05'
down_revision = 'd28ab2660e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Country',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"Country_id_seq"\'::regclass)'), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'Country_pkey')
    )
    # ### end Alembic commands ###
