"""empty message

Revision ID: 8776e7b6b398
Revises: 
Create Date: 2017-01-03 17:40:26.208142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8776e7b6b398'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('NationalITy', sa.String(), nullable=True),
    sa.Column('PlaceofBirth', sa.String(), nullable=True),
    sa.Column('StageID', sa.String(), nullable=True),
    sa.Column('GradeID', sa.String(), nullable=True),
    sa.Column('SectionID', sa.String(), nullable=True),
    sa.Column('Topic', sa.String(), nullable=True),
    sa.Column('Semester', sa.String(), nullable=True),
    sa.Column('Relation', sa.String(), nullable=True),
    sa.Column('raisedhands', sa.Integer(), nullable=True),
    sa.Column('VisITedResources', sa.Integer(), nullable=True),
    sa.Column('AnnouncementsView', sa.Integer(), nullable=True),
    sa.Column('Discussion', sa.Integer(), nullable=True),
    sa.Column('ParentAnsweringSurvey', sa.String(), nullable=True),
    sa.Column('ParentschoolSatisfaction', sa.String(), nullable=True),
    sa.Column('StudentAbsenceDays', sa.String(), nullable=True),
    sa.Column('Class', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sap_t',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('raisedhands', sa.Integer(), nullable=True),
    sa.Column('visitedresources', sa.Integer(), nullable=True),
    sa.Column('announcementsview', sa.Integer(), nullable=True),
    sa.Column('discussion', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sap_t')
    op.drop_table('sap')
    # ### end Alembic commands ###
