"""empty message

Revision ID: ae1c689ec7e0
Revises: 
Create Date: 2016-12-06 16:47:22.885910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae1c689ec7e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'League', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Player_Attributes', type_='foreignkey')
    op.drop_constraint(None, 'Player_Attributes', type_='foreignkey')
    op.drop_constraint(None, 'Team_Attributes', type_='foreignkey')
    op.drop_constraint(None, 'Team_Attributes', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Team_Attributes', 'Team', ['team_api_id'], ['team_api_id'])
    op.create_foreign_key(None, 'Team_Attributes', 'Team', ['team_fifa_api_id'], ['team_fifa_api_id'])
    op.create_foreign_key(None, 'Player_Attributes', 'Player', ['player_fifa_api_id'], ['player_fifa_api_id'])
    op.create_foreign_key(None, 'Player_Attributes', 'Player', ['player_api_id'], ['player_api_id'])
    op.create_foreign_key(None, 'Match', 'Player', ['away_player_3'], ['player_api_id'])
    op.create_foreign_key(None, 'Match', 'Player', ['home_player_7'], ['player_api_id'])
    op.create_foreign_key(None, 'Match', 'country', ['country_id'], ['id'])
    op.create_foreign_key(None, 'Match', 'Player', ['home_player_9'], ['player_api_id'])
    op.create_foreign_key(None, 'Match', 'Player', ['away_player_2'], ['player_api_id'])
    op.create_foreign_key(None, 'Match', 'Team', ['home_team_api_id'], ['team_api_id'])
    op.create_foreign_key(None, 'Match', 'Team', ['away_team_api_id'], ['team_api_id'])
    op.create_foreign_key(None, 'Match', 'Player', ['away_player_4'], ['player_api_id'])
    op.create_foreign_key(None, 'Match', 'Player', ['away_player_7'], ['player_api_id'])
    op.create_foreign_key(None, 'Match', 'Player', ['away_player_6'], ['player_api_id'])
    op.create_foreign_key(None, 'Match', 'Player', ['away_player_9'], ['player_api_id'])
    op.create_foreign_key(None, 'Match', 'Player', ['home_player_5'], ['player_api_id'])
    op.create_foreign_key(None, 'Match', 'Player', ['home_player_1'], ['player_api_id'])
    op.create_foreign_key(None, 'Match', 'Player', ['home_player_6'], ['player_api_id'])
    op.create_foreign_key(None, 'Match', 'Player', ['home_player_2'], ['player_api_id'])
    op.create_foreign_key(None, 'Match', 'Player', ['home_player_3'], ['player_api_id'])
    op.create_foreign_key(None, 'Match', 'Player', ['home_player_10'], ['player_api_id'])
    op.create_foreign_key(None, 'Match', 'Player', ['home_player_8'], ['player_api_id'])
    op.create_foreign_key(None, 'Match', 'League', ['league_id'], ['id'])
    op.create_foreign_key(None, 'Match', 'Player', ['away_player_1'], ['player_api_id'])
    op.create_foreign_key(None, 'Match', 'Player', ['away_player_8'], ['player_api_id'])
    op.create_foreign_key(None, 'Match', 'Player', ['away_player_5'], ['player_api_id'])
    op.create_foreign_key(None, 'Match', 'Player', ['home_player_11'], ['player_api_id'])
    op.create_foreign_key(None, 'Match', 'Player', ['home_player_4'], ['player_api_id'])
    op.create_foreign_key(None, 'Match', 'Player', ['away_player_11'], ['player_api_id'])
    op.create_foreign_key(None, 'Match', 'Player', ['away_player_10'], ['player_api_id'])
    op.create_foreign_key(None, 'League', 'country', ['country_id'], ['id'])
    # ### end Alembic commands ###
