"""empty message

Revision ID: d28ab2660e71
Revises: 0cd2540a295f
Create Date: 2016-12-07 15:51:35.279269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28ab2660e71'
down_revision = '0cd2540a295f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('NationalITy', sa.String(), nullable=True),
    sa.Column('PlaceofBirth', sa.String(), nullable=True),
    sa.Column('StageID', sa.String(), nullable=True),
    sa.Column('GradeID', sa.String(), nullable=True),
    sa.Column('SectionID', sa.String(), nullable=True),
    sa.Column('Topic', sa.String(), nullable=True),
    sa.Column('Semester', sa.String(), nullable=True),
    sa.Column('Relation', sa.String(), nullable=True),
    sa.Column('raisedhands', sa.Integer(), nullable=True),
    sa.Column('VisITedResources', sa.Integer(), nullable=True),
    sa.Column('AnnouncementsView', sa.Integer(), nullable=True),
    sa.Column('Discussion', sa.Integer(), nullable=True),
    sa.Column('ParentAnsweringSurvey', sa.String(), nullable=True),
    sa.Column('ParentschoolSatisfaction', sa.String(), nullable=True),
    sa.Column('StudentAbsenceDays', sa.String(), nullable=True),
    sa.Column('Class', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sap')
    # ### end Alembic commands ###
